# site settings
title: Dewi Oktaviani
subtitle: Senior Data Engineer
email: oktaviani.dewi@gmail.com
description: A Senior Data Engineer
baseurl: "/blog" 
url: # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
city: Surabaya
# state: TN
# zip_code: 55555
country: Indonesia
phone: (62) 896-836-117-30

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/oktavianidewi
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/datengweekly
  LinkedIn: https://www.linkedin.com/in/dewi-nurfitri-oktaviani-6b450b22/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
